# Weights for Diversity Descriptor
# Choose values in range [0,1]

#weights
a_background_abs_w: 0.2 # average background height
a_background_std_w: 0.2 # average standard deviation of background
n_unique_times_w: 0.5   # number of unique migration times
n_unique_masses_w: 0.5  # number of unique masses
v_unique_masses_w: 0.03    # vector of binned masses (binary) [needs to be devided by number of bins (33)]


#max values should be 90th percentile
a_background_abs_max: 50 # average background height
a_background_std_max: 50 # average standard deviation of background
n_unique_times_max: 50   # number of unique migration times
n_unique_masses_max: 100 # number of unique masses
v_unique_masses_max: 1   # vector of binned masses (binary)