90 : b-Alanine
112 : Cytosine
104 : AIB
156 : Histidine
136 : Adenine
133 : Gly-Gly
76 : Glycine
152 : Guanine
190 : Gly-Gly-Gly
244 : Cytidine
118 : Valine_Ival
106 : Serine
132 : Leucine
268 : Adenosine
265 : Phe-Val
148 : Glutamic
358 : Leu-Leu-Leu
134 : Aspartic
284 : Guanosine
113 : Uracil
243 : Thymidine
245 : Uridine
87 : 3-Aminopyrrolidine_IS-1
182 : L-Methionine_Sulfone_IS-2
