# Hologram definitions
hologram_file_extensions: ['.tif']
raw_hologram_resolution: [2048, 2048]
preproc_resolution: [1024, 1024]
# TOGA configs
raw_batch_dir: False          # TOGA needs to know absolute path
experiment_outputs_prefix: "" # Allow TOGA to redirect experiment outputs
# Output directories
experiment_dirs:
  hologram_dir: 'Holograms'
  label_dir: 'labels'
  preproc_dir: 'holograms_preproc'
  baseline_dir: 'holograms_baseline_subtracted'
  validate_dir: 'validate'
  track_dir: 'tracks'
  evaluation_dir: 'tracker_eval'
  features_dir: 'features'
  feature_plot_dir: 'feature_plots'
  output_plot_dir: 'output_plots'
  predict_dir: 'predict'
  asdp_dir: 'asdp'
  timestamp_dir: 'timestamps'
batch_dirs:
  output_dir: 'output'
  classifier_dir: 'classifier_output'
  point_eval_dir: 'point_eval'
  track_eval_dir: 'track_eval'
# Validate step configs
validate:
  mp_batch_size: 25
  min_holograms: 50
  min_distinct_holograms: 0
  baseline_colormap: 'viridis_r'
  baseline_vmin: 0.1
  baseline_vmax: 95.0
  baseline_subtracted_ext: '.png'
  # See docs/presentations/Thresholds_Jake_07202020.pptx for below thresholds
  intensity_lbound: 20
  intensity_ubound: 130
  diff_lbound: 0
  diff_ubound: 2.4
  density_downscale_shape: [128, 128]   # Size to downscale images to during density estimation
  density_block_size: 16                # Size of each block to compute Std. Dev. for
  density_thresh_block: 1.0             # Std. Dev. value for 1 block. At or above this value is considered "dense"
  density_thresh_exp: 0.1               # Proportion of blocks in 1st image that must be dense for experiment to be considered dense
# Data Quality Estimate (DQE) config
data_quality:
  weights:                   # For each validation check, assign a numeric weight
    intensity_valid: 0.15    # Weight associated with a valid mean frame brightness
    diff_valid: 0.15         # Weight associated with a valid mean per-frame diff
    density_valid: 0.1       # Weight associated with a valid number particle density estimate
    fourier_valid: 0.1       # Weight associated with a valid Fourier spectrum for the laser
    no_duplicates: 0.25      # Weight associated with having no duplicated DHM frames
    no_bad_files: 0.25       # Weight associated with having no missing or corrupt hologram tiffs
# Tracker step configs
tracker_settings:
  track_plot: True
  debug_video: False
  skip_frames: 0
  diff_comp:            # Parameters affecting the diff image (input to clustering)
    absthresh: 0        # Throw at diff points not meeting absolute pixel difference
    pcthresh: 99.9      # Throw out percentage of total pixels
  clustering:
    dbscan:             # Out of the box dbscan parameters
      epsilon_px: 17.662197339147514
      min_weight: 74.26919199392793
    filters:            # Post filters on the clustering independent of clustering algorithm
      min_px: 3         # Filter out whole clusters not meeting raw pixel count
  tracking:                   # Parameters controlling how clusters get mapped to particles in tracks
    use_acceleration : False  # If true, include acceleration in track projections
    max_init_dist: 25         # Only consider second-point clusters within this pixel distance from the first point
    max_assignment_dist : 20  # Only consider clusters within this pixel distance of a track projection
    max_projected_frames : 3  # Allow loss of tracking for this many frames before terminating a track
    min_track_obs : 10        # Omit tracks with fewer than this many non-null frames
  LAPtracking:
    max_assignment_dist: 32.354400076358544
    max_skip: 17.865001514634642
    min_track_obs: 10
# Point and track evaluation step configs
evaluation:
  tracks:
    macro_score_report_file: "metrics_macro_avg.json"
    micro_score_report_file: "metrics_micro_avg.json"
    track_matcher: 'ptc_spatial_match'
    hist_metrics: ['alpha', 'beta', 'TP_tracks', 'FN_tracks', 'FP_tracks', 'JSC_tracks']
    simple_spatial_match_args:
      track_eval_dist_threshold: 25   # Spatial threshold in number of pixels
      track_association_overlap_threshold: 0.75  # Proportion of proposed track that must match true track
    ptc_spatial_match_args:
      eps: 10
  points:
    means_score_report_file: "metric_means.json"
    raw_distributions_file: "raw_distributions.json"
    by_track_report_file: "recall_by_track.json"
    point_eval_dist_threshold: 25  # Spatial threshold in number of pixels
    hist_metrics: ['precision', 'recall', 'f_1', 'f_0.5', 'f_0.25']
  use_interpolated_tracks: False
  histogram_bins: 20
# Features step configs
features:
  tracks:
    rename:
      #  From : to
      Times   : frame
      Track_ID: track
  output    : data_track_features.csv
  whitelist : []  # Specify a list of features to include. Do not also define a blacklist.
  blacklist : ['bbox_area_mean', 'bbox_area_median', 'bbox_area_max', 'bbox_area_min']  # Specify a list of features to exclude. Do not also define a whitelist.
  drop      : ['frame', 'Particles_Estimated_Position', 'Particles_Bbox'] # Drop from the track feature dicts before CSV write and return
# Classifier step configs
classifier:
  model_savepath: 'track_classifier.pickle'   # Filename for saved model to classifier_dir
  do_cross_validation: True                 # Whether to perform cross validation on training set
  cv_folds: 5                               # Number of folds for cross validation
  motility_threshold: 0.7                   # Minimum probability threshold for motility classification
# Mugshot configs (within asdp)
mugshot:
  fixed_width: 0 # If set to 0, will dynamically crop to tracker bounding box
  max_pertrack: 5 # If set to 0, all mugshots possible will be generated
  padding: 50 # Padding on the radius of the dynamic bounding box when fixed_width == 0
# Science Utility Estimate
sue:
  weights:
    n_motile: 1.          # Relative weight for number of motile tracks
  extrema:                # Maximum allowed values for each of the SUE factors
    n_motile: 50
# Diversity Descriptor
dd:
  weights:
    n_motile: 0.8         # Relative weight for number of motile tracks
    n_non_motile: 0.1     # Relative weighting for non-motile tracks
    n_other: 0.1          # Relative weighting for ambiguous tracks
  extrema:                # Maximum allowed values for each of the DD factors
    n_motile: 50
    n_non_motile: 50
    n_other: 50
# Fourier validation config
fourier_image:
  params:
    dp: 1
    minDist: 25
    param1: 5
    param2: 10
    minRadius: 10
    maxRadius: 25
    row_epsilon: 10
    col_epsilon: 10
    radius_epsilon: 10
    intensity_epsilon: 10
  ref_points:
    0:
      row: 50
      col: 50
      radius: 16
      intensity: 10
    1:
      row: 76
      col: 76
      radius: 15
      intensity: 10
    2:
      row: 23
      col: 24
      radius: 15
      intensity: 10
