hologram_file_extensions: ['.tif']
raw_hologram_resolution: [2200, 3208, 3]
resize_factor: 1
mugshot_padding: 25         # Width of padding for mugshot cropping.
# Instrument configs
instrument:
  min_perc: 99.5            # Minimum percentile thresholding for mugshotting. Discarded if Otsu determines a higher threshold.
  max_dn: 255               # Maximum DN value of raw data. Used for normalization of pixel calculations.
  red_band_weight: 0.36     # Percentage weight applied to each RGB band. RGB must sum to 1.
  green_band_weight: 0.287  # Percentage weight applied to each RGB band. RGB must sum to 1.
  blue_band_weight: 0.353   # Percentage weight applied to each RGB band. RGB must sum to 1.
# Output directories
experiment_dirs:
  hologram_dir: 'raw'
  label_dir: 'labels'
  track_dir: 'tracks'
  asdp_dir: 'asdp'
  timestamp_dir: 'timestamps'
batch_dirs:
  output_dir: 'output'
raw_batch_dir: False # TOGA needs to know absolute path; optionally override timestamp on dir
# Validate step configs
validate:
  min_holograms: 1
  max_holograms: 50
# Tracker step configs
tracker:
  min_bbox_area: 500
  max_bbox_area: 50000
# ASDP step configs
asdp:
  r_activation_thresh: 50
  g_activation_thresh: 50
  b_activation_thresh: 50
# Science Utility Estimate
sue:
  weights:
    fill_perc: 0.8     # Relative weight for contour fill
    perim_ratio: 0.0   # Relative weight for ratio between contour and hull
    eccentricity: 0.1  # Relative weight for eccentricity 
    red_99th: 0.05     # Relative weight for Red channel 99th perc intensity
    blue_99th: 0       # Relative weight for Blue channel 99th perc intensity
    green_99th: 0.05   # Relative weight for Green channel 99th perc intensity
  extrema:
    fill_perc: 0.7     # Percentage is bound 0 to 1
    perim_ratio: 1.0   # 1 is perfect match between contour and hull, rougher contour near 0
    eccentricity: 1.0  # 0 is a round ellipse, 1 is an infinitely long ellipse
    red_99th: 255      # 255 is maximum intensity
    blue_99th: 255     # 255 is maximum intensity
    green_99th: 255    # 255 is maximum intensity
# Diversity Descriptor
dd:
  weights:
    fill_perc: 0.3     # Relative weight for contour fill
    perim_ratio: 0.1   # Relative weight for ratio between contour and hull
    eccentricity: 0.3  # Relative weight for eccentricity
    red_99th: 0.1      # Relative weight for Red channel 99th perc intensity
    blue_99th: 0.1     # Relative weight for Blue channel 99th perc intensity
    green_99th: 0.1    # Relative weight for Green channel 99th perc intensity
  extrema:
    fill_perc: 0.7     # Percentage is bound 0 to 1
    perim_ratio: 1.0   # 1 is perfect match between contour and hull, rougher contour near 0
    eccentricity: 1.0  # 0 is a round ellipse, 1 is an infinitely long ellipse
    red_99th: 255      # 255 is maximum intensity
    blue_99th: 255     # 255 is maximum intensity
    green_99th: 255    # 255 is maximum intensity