debug: True
hologram_file_extensions: ['.tiff']
min_holograms: 1
raw_hologram_resolution: [2200, 3208, 3]
resize_factor: 1
mugshot_padding: 25
num_mugshots: 5 # Number of mugshots per-track. If set to 0, all mugshots possible will be generated
min_organism_size: 100
binary_threshold: 0.1
experiment_dirs:
    hologram_dir: 'Holograms'
    label_dir: 'labels'
    preproc_dir: 'holograms_preproc'
    baseline_dir: 'holograms_baseline_subtracted'
    diff_dir: 'holograms_diff_temp'
    diffvis_dir: 'holograms_diffvis_temp'
    trail_dir: 'holograms_trail_temp'
    validate_dir: 'validate'
    track_dir: 'tracks'
    evaluation_dir: 'tracker_eval'
    features_dir: 'features'
    feature_plot_dir: 'feature_plots'
    output_plot_dir: 'output_plots'
    predict_dir: 'predict'
    asdp_dir: 'asdp'
    timestamp_dir: 'timestamps'
batch_dirs:
    output_dir: 'output'
raw_batch_dir: False # TOGA needs to know absolute path; optionally override timestamp on dir
experiment_outputs_prefix: "" # Allow TOGA to redirect experiment outputs
allow_plotting: False
outfile: 'metrics.csv'
sue:  # Science Utility Estimate
  weights:
    n_motile: 1.         # Relative weight for number of motile tracks
  extrema:  # Maximum allowed values for each of the SUE factors
    n_motile: 50
dd:  # Diversity Descriptor
  weights:
    n_motile: 0.8         # Relative weight for number of motile tracks
    n_non_motile: 0.1     # Relative weighting for non-motile tracks
    n_other: 0.1          # Relative weighting for ambiguous tracks
  extrema:  # Maximum allowed values for each of the DD factors
    n_motile: 50
    n_non_motile: 50
    n_other: 50
